services:
  postgres:
    image: "postgres:18"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
# docker compose exec postgres sh
# hostname -i

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "54321:80"
    depends_on:
      - postgres

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_local
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

  # Serviço auxiliar para criar o bucket automaticamente
  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set meu_minio http://minio:9000 root password;
      /usr/bin/mc mb meu_minio/video-bucket;
      exit 0;
      "
volumes:
  postgres-data:
  minio_data:
  