sonar.sources=cmd,internal
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=cmd/**/main.go,**/adapters/db/**,internal/pkg/databases/**,internal/pkg/messaging/**,internal/pkg/observability/**,internal/pkg/storage/**,**/adapters/messaging/**,**/migrations/**
sonar.exclusions=**/vendor/**,**/*.exe,**/outputs/**,**/temp/**,**/uploads/**