global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: auth-api
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-api:8081"]

  - job_name: upload-api
    metrics_path: /metrics
    static_configs:
      - targets: ["upload-api:8082"]

  - job_name: video-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["video-worker:8083"]
